/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuemSomosNossaHistoriaRouteImport } from './routes/quem-somos.nossa-historia'
import { Route as QuemSomosEquipeRouteImport } from './routes/quem-somos.equipe'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosNossaHistoriaRoute = QuemSomosNossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => QuemSomosRoute,
} as any)
const QuemSomosEquipeRoute = QuemSomosEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => QuemSomosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRouteWithChildren
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projetos'
    | '/quem-somos'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projetos'
    | '/quem-somos'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
  id:
    | '__root__'
    | '/'
    | '/projetos'
    | '/quem-somos'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetosRoute: typeof ProjetosRoute
  QuemSomosRoute: typeof QuemSomosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/nossa-historia': {
      id: '/quem-somos/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/quem-somos/nossa-historia'
      preLoaderRoute: typeof QuemSomosNossaHistoriaRouteImport
      parentRoute: typeof QuemSomosRoute
    }
    '/quem-somos/equipe': {
      id: '/quem-somos/equipe'
      path: '/equipe'
      fullPath: '/quem-somos/equipe'
      preLoaderRoute: typeof QuemSomosEquipeRouteImport
      parentRoute: typeof QuemSomosRoute
    }
  }
}

interface QuemSomosRouteChildren {
  QuemSomosEquipeRoute: typeof QuemSomosEquipeRoute
  QuemSomosNossaHistoriaRoute: typeof QuemSomosNossaHistoriaRoute
}

const QuemSomosRouteChildren: QuemSomosRouteChildren = {
  QuemSomosEquipeRoute: QuemSomosEquipeRoute,
  QuemSomosNossaHistoriaRoute: QuemSomosNossaHistoriaRoute,
}

const QuemSomosRouteWithChildren = QuemSomosRoute._addFileChildren(
  QuemSomosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetosRoute: ProjetosRoute,
  QuemSomosRoute: QuemSomosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
