/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoDoarRouteImport } from './routes/como-doar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuemSomosIndexRouteImport } from './routes/quem-somos.index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as QuemSomosTransparenciaRouteImport } from './routes/quem-somos.transparencia'
import { Route as QuemSomosNossaHistoriaRouteImport } from './routes/quem-somos.nossa-historia'
import { Route as QuemSomosEquipeRouteImport } from './routes/quem-somos.equipe'
import { Route as ProjetosPalavrasQueTransformamRouteImport } from './routes/projetos.palavras-que-transformam'
import { Route as ProjetosLeituraEmComunidadeRouteImport } from './routes/projetos.leitura-em-comunidade'
import { Route as ProjetosEstanteVivaRouteImport } from './routes/projetos.estante-viva'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoDoarRoute = ComoDoarRouteImport.update({
  id: '/como-doar',
  path: '/como-doar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosIndexRoute = QuemSomosIndexRouteImport.update({
  id: '/quem-somos/',
  path: '/quem-somos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosTransparenciaRoute = QuemSomosTransparenciaRouteImport.update({
  id: '/quem-somos/transparencia',
  path: '/quem-somos/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosNossaHistoriaRoute = QuemSomosNossaHistoriaRouteImport.update({
  id: '/quem-somos/nossa-historia',
  path: '/quem-somos/nossa-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosEquipeRoute = QuemSomosEquipeRouteImport.update({
  id: '/quem-somos/equipe',
  path: '/quem-somos/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosPalavrasQueTransformamRoute =
  ProjetosPalavrasQueTransformamRouteImport.update({
    id: '/projetos/palavras-que-transformam',
    path: '/projetos/palavras-que-transformam',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjetosLeituraEmComunidadeRoute =
  ProjetosLeituraEmComunidadeRouteImport.update({
    id: '/projetos/leitura-em-comunidade',
    path: '/projetos/leitura-em-comunidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjetosEstanteVivaRoute = ProjetosEstanteVivaRouteImport.update({
  id: '/projetos/estante-viva',
  path: '/projetos/estante-viva',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-doar': typeof ComoDoarRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/estante-viva': typeof ProjetosEstanteVivaRoute
  '/projetos/leitura-em-comunidade': typeof ProjetosLeituraEmComunidadeRoute
  '/projetos/palavras-que-transformam': typeof ProjetosPalavrasQueTransformamRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-doar': typeof ComoDoarRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/estante-viva': typeof ProjetosEstanteVivaRoute
  '/projetos/leitura-em-comunidade': typeof ProjetosLeituraEmComunidadeRoute
  '/projetos/palavras-que-transformam': typeof ProjetosPalavrasQueTransformamRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/quem-somos': typeof QuemSomosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-doar': typeof ComoDoarRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/estante-viva': typeof ProjetosEstanteVivaRoute
  '/projetos/leitura-em-comunidade': typeof ProjetosLeituraEmComunidadeRoute
  '/projetos/palavras-que-transformam': typeof ProjetosPalavrasQueTransformamRoute
  '/quem-somos/equipe': typeof QuemSomosEquipeRoute
  '/quem-somos/nossa-historia': typeof QuemSomosNossaHistoriaRoute
  '/quem-somos/transparencia': typeof QuemSomosTransparenciaRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-doar'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/noticias/$slug'
    | '/projetos/estante-viva'
    | '/projetos/leitura-em-comunidade'
    | '/projetos/palavras-que-transformam'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-doar'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/noticias/$slug'
    | '/projetos/estante-viva'
    | '/projetos/leitura-em-comunidade'
    | '/projetos/palavras-que-transformam'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/como-doar'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/noticias/$slug'
    | '/projetos/estante-viva'
    | '/projetos/leitura-em-comunidade'
    | '/projetos/palavras-que-transformam'
    | '/quem-somos/equipe'
    | '/quem-somos/nossa-historia'
    | '/quem-somos/transparencia'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoDoarRoute: typeof ComoDoarRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ProjetosEstanteVivaRoute: typeof ProjetosEstanteVivaRoute
  ProjetosLeituraEmComunidadeRoute: typeof ProjetosLeituraEmComunidadeRoute
  ProjetosPalavrasQueTransformamRoute: typeof ProjetosPalavrasQueTransformamRoute
  QuemSomosEquipeRoute: typeof QuemSomosEquipeRoute
  QuemSomosNossaHistoriaRoute: typeof QuemSomosNossaHistoriaRoute
  QuemSomosTransparenciaRoute: typeof QuemSomosTransparenciaRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  QuemSomosIndexRoute: typeof QuemSomosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-doar': {
      id: '/como-doar'
      path: '/como-doar'
      fullPath: '/como-doar'
      preLoaderRoute: typeof ComoDoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/': {
      id: '/quem-somos/'
      path: '/quem-somos'
      fullPath: '/quem-somos/'
      preLoaderRoute: typeof QuemSomosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/transparencia': {
      id: '/quem-somos/transparencia'
      path: '/quem-somos/transparencia'
      fullPath: '/quem-somos/transparencia'
      preLoaderRoute: typeof QuemSomosTransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/nossa-historia': {
      id: '/quem-somos/nossa-historia'
      path: '/quem-somos/nossa-historia'
      fullPath: '/quem-somos/nossa-historia'
      preLoaderRoute: typeof QuemSomosNossaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/equipe': {
      id: '/quem-somos/equipe'
      path: '/quem-somos/equipe'
      fullPath: '/quem-somos/equipe'
      preLoaderRoute: typeof QuemSomosEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/palavras-que-transformam': {
      id: '/projetos/palavras-que-transformam'
      path: '/projetos/palavras-que-transformam'
      fullPath: '/projetos/palavras-que-transformam'
      preLoaderRoute: typeof ProjetosPalavrasQueTransformamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/leitura-em-comunidade': {
      id: '/projetos/leitura-em-comunidade'
      path: '/projetos/leitura-em-comunidade'
      fullPath: '/projetos/leitura-em-comunidade'
      preLoaderRoute: typeof ProjetosLeituraEmComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/estante-viva': {
      id: '/projetos/estante-viva'
      path: '/projetos/estante-viva'
      fullPath: '/projetos/estante-viva'
      preLoaderRoute: typeof ProjetosEstanteVivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoDoarRoute: ComoDoarRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ProjetosEstanteVivaRoute: ProjetosEstanteVivaRoute,
  ProjetosLeituraEmComunidadeRoute: ProjetosLeituraEmComunidadeRoute,
  ProjetosPalavrasQueTransformamRoute: ProjetosPalavrasQueTransformamRoute,
  QuemSomosEquipeRoute: QuemSomosEquipeRoute,
  QuemSomosNossaHistoriaRoute: QuemSomosNossaHistoriaRoute,
  QuemSomosTransparenciaRoute: QuemSomosTransparenciaRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  QuemSomosIndexRoute: QuemSomosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
